
FAIL SyncAccessHandle.close is idempotent promise_test: Unhandled rejection with value: object "NotSupportedError: The operation is not supported."
FAIL SyncAccessHandle.close is idempotent when called immediately promise_test: Unhandled rejection with value: object "NotSupportedError: The operation is not supported."
FAIL SyncAccessHandle.read fails after SyncAccessHandle.close settles promise_test: Unhandled rejection with value: object "NotSupportedError: The operation is not supported."
FAIL SyncAccessHandle.read fails immediately after calling SyncAccessHandle.close promise_test: Unhandled rejection with value: object "NotSupportedError: The operation is not supported."
FAIL SyncAccessHandle.write fails after SyncAccessHandle.close settles promise_test: Unhandled rejection with value: object "NotSupportedError: The operation is not supported."
FAIL SyncAccessHandle.write fails immediately after calling SyncAccessHandle.close promise_test: Unhandled rejection with value: object "NotSupportedError: The operation is not supported."
FAIL SyncAccessHandle.flush fails after SyncAccessHandle.close settles promise_test: Unhandled rejection with value: object "NotSupportedError: The operation is not supported."
FAIL SyncAccessHandle.flush fails immediately after calling SyncAccessHandle.close promise_test: Unhandled rejection with value: object "NotSupportedError: The operation is not supported."
FAIL SyncAccessHandle.getSize fails after SyncAccessHandle.close settles promise_test: Unhandled rejection with value: object "NotSupportedError: The operation is not supported."
FAIL SyncAccessHandle.getSize fails immediately after calling SyncAccessHandle.close promise_test: Unhandled rejection with value: object "NotSupportedError: The operation is not supported."
FAIL SyncAccessHandle.truncate fails after SyncAccessHandle.close settles promise_test: Unhandled rejection with value: object "NotSupportedError: The operation is not supported."
FAIL SyncAccessHandle.truncate fails immediately after calling SyncAccessHandle.close promise_test: Unhandled rejection with value: object "NotSupportedError: The operation is not supported."

